{"name": "test_add_course_fail[case0]", "status": "passed", "attachments": [{"name": "log", "source": "b162875d-f83d-4127-b8cf-bf54c4787e98-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '验证码错误', 'verificate_code': 'P69YYY', 'expected': '该加课码不存在或者已经失效'}"}], "start": 1604461908964, "stop": 1604461911311, "uuid": "21738a9f-4b0b-46a6-bc13-5a084fa6a2f2", "historyId": "08f41c2e50fa3306047a98754e972cd3", "testCaseId": "160dedc24855c98b250adf59f7822f75", "fullName": "testcase.test_02add_course.TestAddCourse#test_add_course_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_02add_course"}, {"name": "subSuite", "value": "TestAddCourse"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "55631-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_02add_course"}]}